# fly.toml app configuration file generated for poc-ollama-server on 2024-04-28T15:30:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poc-ollama-server'
primary_region = 'gru'

[build]
  image = 'ollama/ollama'

[[mounts]]
  source = 'models'
  destination = '/root/.ollama'
  initial_size = '50gb'

[http_service]
  internal_port = 11434
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-4x'
